version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/var/log/regression:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network
    restart: unless-stopped
    depends_on:
      - loki

  # Nginx proxy for ngrok tunnel
  nginx:
    image: nginx:alpine
    ports:
      - "3101:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - loki-network
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  loki-data:

networks:
  loki-network:
    driver: bridge
