server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: regression-tests
    static_configs:
      - targets:
          - localhost
        labels:
          job: regression-tests
          service: regression-testing-framework
          __path__: /mnt/d/AI_bot/Release_Deployment_Bot/github-ci-bot_Changes/RegressionTesting/logs/regression-tests.log

    # Pipeline for processing JSON logs
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            environment: environment
            screenshot: screenshot
      
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      
      - labels:
          level: level
          service: service
          environment: environment
